services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: next_sf_poc
        ports:
            - "3000:3000"
        env_file:
            - .env.local
