import type { Metadata } from "next";

import { getServerSession } from "next-auth";

import { Box } from "@mui/material";

import "./globals.css";

import SessionProvider from "./components/SessionProvider";
import NavMenu from "./components/NavMenu";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const session = await getServerSession();

    return (
        <html lang="en">
            <body>
                <SessionProvider session={session}>
                    <Box
                        component="main"
                        sx={{
                            height: "100vh",
                            display: "flex",
                            justifyContent: "center",
                            alignItems: "center",
                            flexDirection: "column",
                            color: "white",
                            textAlign: "center",
                        }}
                    >
                        <NavMenu />
                        {children}
                    </Box>
                </SessionProvider>
            </body>
        </html>
    );
}
