import type { Metadata } from "next";

import { getServerSession } from "next-auth";

import "./globals.css";

import SessionProvider from "./components/SessionProvider";
import NavMenu from "./components/NavMenu";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const session = await getServerSession();

    return (
        <html lang="en">
            <body>
                <SessionProvider session={session}>
                    <NavMenu>{children}</NavMenu>
                </SessionProvider>
            </body>
        </html>
    );
}
